routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\GeneralController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\frontend\FrontendController;
use App\Http\Controllers\frontend\OrderController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [FrontendController::class,'index']);
Route::get('/product-detail/{id}',[\App\Http\Controllers\frontend\ProductController::class,'productDetail']);
Route::post('/book-room', [OrderController::class,'checkout']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth']], function () {
    Route::get('/categories', [CategoryController::class, 'index'])->name('categoryList')->middleware('can:categories');
    Route::post('/store-category', [CategoryController::class, 'store'])->name('storeCategory');
    Route::post('edit-category/{id}', [CategoryController::class, 'editcategory']);
    Route::delete('delete-category/{id}', [CategoryController::class, 'deletecategory']);

    Route::get('/sub-categories', [CategoryController::class, 'subcategoryList'])->middleware('can:sub-categories');
    Route::post('/add-sub-categories', [CategoryController::class, 'addsubcategory'])->name('storesubCategory');
    Route::post('/edit-sub-category/{id}', [CategoryController::class, 'Updatesubcategory']);
    Route::delete('delete-sub-category/{id}', [CategoryController::class, 'deleteSubcategory']);

    // role routes
    Route::get('roles', [RoleController::class, 'roles'])->middleware('can:roles');
    Route::get('add-role', [RoleController::class, 'Addrole']);
    Route::post('save-role', [RoleController::class, 'SaveRole'])->name('storeRole');
    Route::get('edit-role/{id}', [RoleController::class, 'EditRole'])->name('editRole')->middleware('can:edit-role');
    Route::post('update-role/{id}', [RoleController::class, 'Update'])->name('UpdateRole');
    Route::delete('delete-role/{id}', [RoleController::class, 'deleteRole']);


    // permissions route
    Route::get('permissions', [PermissionController::class, 'permissions'])->middleware('can:permissions');
    Route::post('/store-permissions', [PermissionController::class, 'storePermissions'])->name('storePermissions');
    Route::post('edit-permission/{id}', [PermissionController::class, 'editpermission']);
    Route::delete('delete-permissions/{id}', [PermissionController::class, 'Deletepermission']);
    // users routes

    Route::get('users', [GeneralController::class, 'users'])->middleware('can:users');
    Route::post('edit-user-profile/{id}', [GeneralController::class, 'EditUser']);
    Route::delete('delete-user/{id}', [GeneralController::class, 'DeleteUser']);




    Route::get('profile', [UserController::class, 'userProfile']);
    Route::post('update-profile', [UserController::class, 'ProfileUpdate'])->name('UpdateProfile');
    Route::post('update-user-location', [UserController::class, 'LocationUpdate'])->name('UpdateUserLocation');




    //
    Route::get('products', [ProductController::class, 'index'])->middleware('can:products');
    Route::get('add-product', [ProductController::class, 'create']);
    Route::post('save-product', [ProductController::class, 'store']);


    //
    Route::get('icons', [GeneralController::class, 'icons'])->name('icons')->middleware('can:icons');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $guarded=[];

    public function Parent(){
       return $this->belongsTo(Category::class, 'parent_id','id');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $categories = Category::all();
        return view('admin.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     */


    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {

        $validatedData = $request->validate(
            [
                'name' => 'required',
                'icon' => 'required',
            ],
            [
                'name.required' => 'Category name is required',
                'icon.required' => 'Icon field is required',
            ]
        );
        Category::create([
            'name' => $request->name,
            'slug' => $request->name,
            'icon' => $request->icon,

        ]);
        return back()->with(['success' => 'Category added successfully.']);
    }
    public function editcategory(Request $request, $id)
    {
        // dd($id);
        $validatedData = $request->validate(
            [
                'name' => 'required',
                'icon' => 'required',
            ],
            [
                'name.required' => 'Category name is required',
                'icon.required' => 'Icon field is required',
            ]
        );
        $editcategory = Category::where('id', $id)->update([
            'name' => $request->name,
            'slug' => $request->name,
            'icon' => $request->icon,
        ]);
        return back()->with(['success' => 'Category updated successfully.']);
    }

    public function deletecategory(Request $request, $id)
    {
        //  dd($id);

        Category::find($id)->delete();
        return back()->with(['success' => 'Category deleted successfully.']);
    }


    public function subcategoryList()
    {
        $all_categories = Category::whereNull('parent_id')->get();
        $categories = Category::with(['Parent'])->whereNotNull('parent_id')->get();
        return view('admin.category.sub_categories', compact('categories', 'all_categories'));
    }
    public function addsubcategory(Request $request)
    {
        // dd($request);
        $validatedData = $request->validate(
            [
                'name' => 'required',
                'icon' => 'required',
                'parent' => 'required',

            ],
            [
                'name.required' => 'Category name is required',
                'icon.required' => 'Icon field is required',
                'parent.required' => 'Parent field is required',

            ]
        );
        Category::create([
            'name' => $request->name,
            'slug' => $request->name,
            'icon' => $request->icon,
            'parent_id' => $request->parent,


        ]);
        return back()->with(['success' => 'Category added successfully.']);
    }

    public function Updatesubcategory(Request $request, $id)
    {

        // dd($id);
        $validatedData = $request->validate(
            [
                'name' => 'required',
                'icon' => 'required',
                'parent' => 'required',

            ],
            [
                'name.required' => 'Category name is required',
                'icon.required' => 'Icon field is required',
                'parent.required' => 'Parent field is required',

            ]
        );
        Category::where('id', $id)->update([
            'name' => $request->name,
            'slug' => $request->name,
            'icon' => $request->icon,
            'parent_id' => $request->parent,
        ]);
        return back()->with(['success' => 'Category updated successfully.']);
    }
    public function deleteSubcategory(Request $request, $id)
    {
        //  dd($id);

        Category::find($id)->delete();
        return back()->with(['success' => 'Category deleted successfully.']);
    }
}

resources/views/admin/category/index.blade.php
@extends('layouts.adminlayout')
@section('title-text', 'Categories')

@section('content')
    <div class="card rounded">
        <div class="card-header d-flex justify-content-between">
            <h4>{{ __('Categories') }}</h4>
            @can('add-category')
                <a href="#" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Add Category</a>
            @endcan
        </div>

        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td>#</td>
                        <td>Name</td>
                        <td>Action</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($categories as $category)
                        <tr>
                            <td>{{ $category->id }}</td>
                            <td>{{ $category->name }}</td>
                            <td>
                                @can('edit-category')
                                    <button class="btn  btn-primary edit-user" data-bs-toggle="modal"
                                        data-bs-target="#editcategory" data-id="{{ $category->id }}"
                                        data-name="{{ $category->name }}" data-icon="{{ $category->icon }}">Edit</button>
                                @endcan
                                @can('delete-category')
                                    <button class="btn  btn-danger delete-cate" data-bs-toggle="modal"
                                        data-bs-target="#deletecategory" data-id="{{ $category->id }}">Delete</button>
                                @endcan
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
            aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <form action="{{ route('admin.storeCategory') }}" method="post">
                    @csrf
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="staticBackdropLabel">Add Category</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-md-12 mb-3">
                                    <label for="name" class="form-label">Name</label>
                                    <input type="text" class="form-control" name="name">
                                </div>
                                {{-- <div class="col-md-6">
                                    <label for="slug">Slug</label>
                                    <input type="text" class="form-control" name="slug">
                                </div> --}}
                                <div class="col-md-12">
                                    <label for="slug" class="form-label">Icon</label>
                                    <textarea name="icon" rows="3" class="form-control"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>

        {{-- edit --}}
        <div class="modal fade" id="editcategory" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
            aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <form method="post" id="editUserForm">
                    @csrf
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="staticBackdropLabel">Edit Category</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-md-12 mb-3">
                                    <label for="name" class="form-label">Name</label>
                                    <input type="text" class="form-control" name="name" id="name">
                                </div>
                                <div class="col-md-12">
                                    <label for="slug" class="form-label">Icon</label>
                                    <textarea name="icon" id="icon" rows="3" class="form-control"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
        <div class="modal fade" id="deletecategory" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
            aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <form method="post" id="deletecate">
                    @csrf
                    @method('DELETE')
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="staticBackdropLabel">Delete Category</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <p>Are you shure to delete this!</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Delete</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>

    </div>

    @push('js')
        <script>
            $(document).ready(function() {
                // Edit User Modal
                $('.edit-user').click(function() {
                    var category_id = $(this).data('id');
                    var name = $(this).data('name');
                    var icon = $(this).data('icon');



                    $('#editUserForm').attr('action', 'edit-category/' + category_id);
                    $('#name').val(name);
                    $('#icon').val(icon);


                });
            });
        </script>
        <script>
            $(document).ready(function() {
                // Edit User Modal
                $('.delete-cate').click(function() {
                    var id = $(this).data('id');
                    $('#deletecate').attr('action', 'delete-category/' + id);

                });
            });
        </script>
    @endpush

@endsection

resources/views/admin/category/sub_categories.blade.php
@extends('layouts.adminlayout')
@section('title-text', 'Sub Categories')

@section('content')
    <div class="card rounded">
        <div class="card-header d-flex justify-content-between">
            <h4>{{ __('Sub Categories') }}</h4>
            @can('add-sub-category')
                <a href="#" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Add Sub
                    Category</a>
            @endcan
        </div>

        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td>#</td>
                        <td>Name</td>
                        <td>Parent Name</td>
                        <td>Action</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($categories as $category)
                        <tr>
                            <td>{{ $category->id }}</td>
                            <td>{{ $category->name }}</td>
                            <td>{{ $category->Parent->name }}</td>
                            <td>
                                @can('edit-sub-category')
                                    <button class="btn  btn-primary edit-user" data-bs-toggle="modal"
                                        data-bs-target="#editcategory" data-id="{{ $category->id }}"
                                        data-name="{{ $category->name }}" data-parent="{{ $category->Parent->id }}"
                                        data-icon="{{ $category->icon }}">Edit</button>
                                @endcan
                                @can('delete-sub-category')
                                    <button class="btn  btn-danger delete-cate" data-bs-toggle="modal"
                                        data-bs-target="#deletecategory" data-id="{{ $category->id }}">Delete</button>
                                @endcan
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
            aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <form action="{{ route('admin.storesubCategory') }}" method="post">
                    @csrf
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="staticBackdropLabel">Add Sub Category</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-md-12 mb-3">
                                    <label for="name" class="form-label">Name</label>
                                    <input type="text" class="form-control" name="name">
                                </div>
                                {{-- <div class="col-md-6 mb-3">
                                    <label for="slug">Slug</label>
                                    <input type="text" class="form-control" name="slug">
                                </div> --}}

                                <div class="col-md-12 mb-3">
                                    <label for="name" class="form-label">Parent</label>
                                    <select name="parent" id="parent" class="form-control">
                                        <option value="">--select category--</option>
                                        @foreach ($all_categories as $item)
                                            <option value="{{ $item->id }}">{{ $item->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="col-md-12">
                                    <label for="slug" class="form-label">Icon</label>
                                    <textarea name="icon" rows="3" class="form-control"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
        {{-- edit --}}
        <div class="modal fade" id="editcategory" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
            aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <form method="post" id="editUserForm">
                    @csrf
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="staticBackdropLabel">Edit Sub Category</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-md-12 mb-3">
                                    <label for="name" class="form-label">Name</label>
                                    <input type="text" class="form-control" name="name" id="name">
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="name" class="form-label">Parent</label>
                                    <select name="parent" id="parent" class="form-control">
                                        <option value="">--select category--</option>
                                        @foreach ($all_categories as $item)
                                            <option value="{{ $item->id }}">{{ $item->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="col-md-12">
                                    <label for="slug" class="form-label">Icon</label>
                                    <textarea name="icon" id="icon" rows="3" class="form-control" id="icon"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
        <div class="modal fade" id="deletecategory" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
            aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <form method="post" id="deletecate">
                    @csrf
                    @method('DELETE')
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="staticBackdropLabel">Delete Sub Category</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <p>Are you shure to delete this!</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Delete</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
    @push('js')
        <script>
            $(document).ready(function() {
                // Edit User Modal
                $('.edit-user').click(function() {
                    var category_id = $(this).data('id');
                    var name = $(this).data('name');
                    var icon = $(this).data('icon');
                    var parent = $(this).data('parent');


                    $('#editUserForm').attr('action', 'edit-sub-category/' + category_id);
                    $('#name').val(name);
                    $('#icon').val(icon);
                    $("#parent option[value='" + parent + "']").attr("selected", "selected");

                });
            });
        </script>
        <script>
            $(document).ready(function() {
                // Edit User Modal
                $('.delete-cate').click(function() {
                    var id = $(this).data('id');
                    $('#deletecate').attr('action', 'delete-sub-category/' + id);

                });
            });
        </script>
    @endpush
@endsection