routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\GeneralController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\frontend\FrontendController;
use App\Http\Controllers\frontend\OrderController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [FrontendController::class,'index']);
Route::get('/product-detail/{id}',[\App\Http\Controllers\frontend\ProductController::class,'productDetail']);
Route::post('/book-room', [OrderController::class,'checkout']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth']], function () {
    Route::get('/categories', [CategoryController::class, 'index'])->name('categoryList')->middleware('can:categories');
    Route::post('/store-category', [CategoryController::class, 'store'])->name('storeCategory');
    Route::post('edit-category/{id}', [CategoryController::class, 'editcategory']);
    Route::delete('delete-category/{id}', [CategoryController::class, 'deletecategory']);

    Route::get('/sub-categories', [CategoryController::class, 'subcategoryList'])->middleware('can:sub-categories');
    Route::post('/add-sub-categories', [CategoryController::class, 'addsubcategory'])->name('storesubCategory');
    Route::post('/edit-sub-category/{id}', [CategoryController::class, 'Updatesubcategory']);
    Route::delete('delete-sub-category/{id}', [CategoryController::class, 'deleteSubcategory']);

    // role routes
    Route::get('roles', [RoleController::class, 'roles'])->middleware('can:roles');
    Route::get('add-role', [RoleController::class, 'Addrole']);
    Route::post('save-role', [RoleController::class, 'SaveRole'])->name('storeRole');
    Route::get('edit-role/{id}', [RoleController::class, 'EditRole'])->name('editRole')->middleware('can:edit-role');
    Route::post('update-role/{id}', [RoleController::class, 'Update'])->name('UpdateRole');
    Route::delete('delete-role/{id}', [RoleController::class, 'deleteRole']);


    // permissions route
    Route::get('permissions', [PermissionController::class, 'permissions'])->middleware('can:permissions');
    Route::post('/store-permissions', [PermissionController::class, 'storePermissions'])->name('storePermissions');
    Route::post('edit-permission/{id}', [PermissionController::class, 'editpermission']);
    Route::delete('delete-permissions/{id}', [PermissionController::class, 'Deletepermission']);
    // users routes

    Route::get('users', [GeneralController::class, 'users'])->middleware('can:users');
    Route::post('edit-user-profile/{id}', [GeneralController::class, 'EditUser']);
    Route::delete('delete-user/{id}', [GeneralController::class, 'DeleteUser']);




    Route::get('profile', [UserController::class, 'userProfile']);
    Route::post('update-profile', [UserController::class, 'ProfileUpdate'])->name('UpdateProfile');
    Route::post('update-user-location', [UserController::class, 'LocationUpdate'])->name('UpdateUserLocation');




    //
    Route::get('products', [ProductController::class, 'index'])->middleware('can:products');
    Route::get('add-product', [ProductController::class, 'create']);
    Route::post('save-product', [ProductController::class, 'store']);


    //
    Route::get('icons', [GeneralController::class, 'icons'])->name('icons')->middleware('can:icons');
});

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    //

    public function roles(){
        $roles = Role::all();
        return view('admin.user-management.role.roles', compact('roles'));
    }

    public function Addrole(){
        $permissions = Permission::all();
        return view('admin.user-management.role.add-role', compact('permissions'));

    }


    public function SaveRole(Request $request){
        //   dd($request);
        $validatedData = $request->validate(
            [
                'name' => 'required',
                'guard_name' => 'required',

            ],
            [
                'name.required' => 'Role name is required',
                'guard_name.required' => 'Guard name is required',

            ]
        );
        $role = Role::create([
            'name' => $request->name,
            'guard_name' => $request->guard_name,
            
        ]);
        $role->syncPermissions($request->permissions);
        return redirect()->route('admin.roles')->with(['success' => 'Role added successfully.']);

    }

    public function EditRole($id)
    {

        $role = Role::find($id);
        $permissions = Permission::all();
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id", $id)
            ->pluck('role_has_permissions.permission_id', 'role_has_permissions.permission_id')
            ->all();
        return view('admin.user-management.role.edit-role', compact('role', 'permissions', 'rolePermissions'));
    }


    public function Update(Request $request, $id)
    {

        // dd($request);
        $validatedData = $request->validate(
            [
                'name' => 'required',
            ],
            [
                'name.required' => 'Role name is required',
            ]
        );
        $role = Role::find($id);
        $role->update([
            'name' => $request->name
        ]);

        $role->syncPermissions($request->permissions);
        return redirect()->route('admin.roles')->with(['success' => 'Role updated successfully.']);
    }

    public function deleteRole($id)
    {
        // dd($id);
        Role::find($id)->delete();
        return back()->with(['success' => 'Role deleted successfully.']);

    }
}

resources/views/admin/user-management/role/add-role.blade.php
@extends('layouts.adminlayout')
@section('title-text', 'Roles')

@section('content')
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div class="header-title">
                        <h4 class="card-title">Add Role</h4>
                    </div>
                </div>
                <div class="card-body">
                    <div class="new-user-info">
                        <form method="POST" action="{{ route('admin.storeRole') }}">
                            @csrf
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label class="form-label" for="fname">Role Name:</label>
                                    <input type="text" class="form-control" id="name" name="name"
                                        value="{{ old('name') }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label" for="lname">Guard Name:</label>
                                    <input type="text" class="form-control" id="guard_name" name="guard_name"
                                        value="{{ old('guard_name') }}">
                                </div>
                                <div class="form-group col-md-12">
                                    <label class="form-label" for="add1">Select Permissions:</label>
                                    <select class="js-example-basic-multiple form-control" name="permissions[]"
                                        multiple="multiple">
                                        @foreach ($permissions as $per)
                                            <option value="{{ $per->id }}">{{ $per->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="">
                                <button type="submit" class="btn btn-primary float-end">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @push('js')
        <script>
            $(document).ready(function() {
                $('.js-example-basic-multiple').select2();
            });
        </script>
    @endpush

@endsection

resources/views/admin/user-management/role/edit-role.blade.php
@extends('layouts.adminlayout')
@section('title-text', 'Roles')

@section('content')
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div class="header-title">
                        <h4 class="card-title">Edit Role</h4>
                    </div>
                </div>
                <div class="card-body">
                    <div class="new-user-info">
                        <form method="POST" action="{{ route('admin.UpdateRole',[$role->id]) }}">
                            @csrf
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label class="form-label" for="fname">Role Name:</label>
                                    <input type="text" class="form-control" id="name" name="name"
                                        value="{{ $role->name }}">
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label" for="lname">Guard Name:</label>
                                    <input type="text" class="form-control" id="guard_name"
                                        value="{{ $role->guard_name }}" readonly>
                                </div>
                                <div class="form-group col-md-12">
                                    <label class="form-label" for="add1">Select Permissions:</label>
                                    <select class="js-example-basic-multiple form-control" name="permissions[]"
                                        multiple="multiple">
                                        @foreach ($permissions as $permission)
                                            <option {{ in_array($permission->id, $rolePermissions) ? 'selected' : '' }}>
                                                {{ $permission->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="my-3">
                                <button type="submit" class="btn btn-primary float-end">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @push('js')
        <script>
            $(document).ready(function() {
                $('.js-example-basic-multiple').select2();
            });
        </script>
    @endpush

@endsection

resources/views/admin/user-management/role/roles.blade.php
a@extends('layouts.adminlayout')
@section('title-text', 'Roles')

@section('content')
    <div class="card rounded">
        <div class="card-header d-flex justify-content-between">
            <h4>{{ __('Roles') }}</h4>
            @can('add-role')
                <a href="{{ url('admin/add-role') }}" class="btn btn-primary">Add Role</a>
            @endcan
        </div>

        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td>#</td>
                        <td>Name</td>
                        <td>Action</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($roles as $role)
                        <tr>
                            <td>{{ $role->id }}</td>
                            <td>{{ $role->name }}</td>
                            <td>
                                @can('edit-role')
                                    <a href="{{ url('admin/edit-role/' . $role->id) }}"
                                        class="btn  btn-primary edit-user">Edit</a>
                                @endcan
                                @can('delete-role')
                                    <button class="btn  btn-danger delete-role" data-bs-toggle="modal"
                                        data-bs-target="#deleterole" data-id="{{ $role->id }}">Delete</button>
                                @endcan
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

    </div>
    {{-- delete --}}
    <div class="modal fade" id="deleterole" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <form method="post" id="delete_role">
                @csrf
                @method('DELETE')
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">Delete Role</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p>Are you shure to delete this!</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Delete</button>
                    </div>
                </div>
            </form>

        </div>
    </div>

    @push('js')
        <script>
            $(document).ready(function() {
                // Edit User Modal
                $('.delete-role').click(function() {
                    var id = $(this).data('id');
                    $('#delete_role').attr('action', 'delete-role/' + id);

                });
            });
        </script>
    @endpush
@endsection